version: '3.8'
services:
  config1:
    image: mongo:latest
    container_name: config1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27019:27017"
    volumes:
      - ../data/config1:/data/db
    networks:
      - mongo-cluster

  config2:
    image: mongo:latest
    container_name: config2
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27020:27017"
    volumes:
      - ../data/config2:/data/db
    networks:
      - mongo-cluster

  config3:
    image: mongo:latest
    container_name: config3
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27021:27017"
    volumes:
      - ../data/config3:/data/db
    networks:
      - mongo-cluster    

  shard1_replica1:
    image: mongo:latest
    container_name: shard1_replica1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet","--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27031:27017"
    volumes:
      - ../data/shard1_replica1:/data/db
    networks:
      - mongo-cluster

  shard1_replica2:
    image: mongo:latest
    container_name: shard1_replica2
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27032:27017"
    volumes:
      - ../data/shard1_replica2:/data/db
    networks:
      - mongo-cluster

  shard2_replica1:
    image: mongo:latest
    container_name: shard2_replica1
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet","--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27033:27017"
    volumes:
      - ../data/shard2_replica1:/data/db
    networks:
      - mongo-cluster

  shard2_replica2:
    image: mongo:latest
    container_name: shard2_replica2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27017", "--dbpath", "/data/db"]
    ports:
      - "27034:27017"
    volumes:
      - ../data/shard2_replica2:/data/db
    networks:
      - mongo-cluster

  mongos:
    image: mongo:latest
    container_name: mongos_router
    environment:
      - HOSTIP=${HOSTIP}
    command: mongos --configdb configReplSet/${HOSTIP}:27019,${HOSTIP}:27020,${HOSTIP}:27021 --bind_ip 0.0.0.0 --port 27017
    ports:
      - "27041:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
